version: '2'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: minhasenha123
      MYSQL_DATABASE: apinotes
      MYSQL_USER: apinotes
      MYSQL_PASSWORD: minhasenha123
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - '3307:3306'
networks:
  app-network:
    driver: bridge
